version: '3.8'

services:
  rasa:
    build: .
    ports:
      - "${PORT}:${PORT}"
    command: >
      rasa run --enable-api 
      --cors "*" 
      --credentials credentials_railway.yml 
      --port ${PORT}
    environment:
      - PORT=${PORT}
      - FACEBOOK_VERIFY=${FACEBOOK_VERIFY}
      - FACEBOOK_SECRET=${FACEBOOK_SECRET}
      - FACEBOOK_PAGE_ACCESS_TOKEN=${FACEBOOK_PAGE_ACCESS_TOKEN}
    restart: always

  actions:
    build: .
    ports:
      - "5055:5055"
    command: rasa run actions --port 5055
    restart: always 