[build]
builder = "DOCKERFILE"
dockerfilePath = "docker-compose.yml"

[deploy]
startCommand = "docker-compose up"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
RASA_URL = "http://rasa:5005"

[[services]]
name = "rasa"
envVarPrefix = "RASA"
startCommand = "rasa run --enable-api --cors \"*\" --credentials credentials_railway.yml --port $PORT"

[[services]]
name = "actions"
envVarPrefix = "ACTIONS"
startCommand = "rasa run actions --port 5055" 