[build]
builder = "NIXPACKS"
buildCommand = "pip install --upgrade pip setuptools && python -m rasa train"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "rasa"
envVarPrefix = "RASA"
startCommand = "rasa run --enable-api --cors \"*\" --credentials credentials_railway.yml --port $PORT"

[[services]]
name = "actions"
envVarPrefix = "ACTIONS"
startCommand = "rasa run actions --port 5055" 